### ISSUE TITLE
Is there any provision to mention custom branch

### ISSUE THREAD

**Issue by shubham-elanco** [mikaelvesavuori/dorametrix-action#1]
As per docs It only works on main branch. Is there any way I can provide custom branch ?

**Comment by mikaelvesavuori** [comment]
Hi @shubham-elanco!

I'm not quite sure what you are referring to here. No mention is made of any specific branch.

How you want to use the Dorametrix action is up to you and your specific GitHub Actions workflow. See this link, for example, for more information: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters.

Know that you can be quite flexible with Dorametrix itself, too, if you look at the docs: https://github.com/mikaelvesavuori/dorametrix?tab=readme-ov-file#configuration.

I will close this, as this is neither a feature request nor a bug.
